# Generated by Django 4.2.2 on 2023-06-16 15:38

import Tamarit.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('monuments', 'Monuments historiques'), ('museums', "Musées et galeries d'art"), ('nature', 'Sites naturels'), ('religious', 'Sites religieux'), ('archaeological', 'Sites archéologiques'), ('attractions', "Parcs d'attractions"), ('gardens', 'Jardins et parcs'), ('beaches', 'Plages et stations balnéaires'), ('historic', 'Villes et quartiers historiques'), ('cultural', 'Sites culturels et patrimoniaux')], max_length=50)),
                ('theme', models.CharField(choices=[('history', 'Histoire et patrimoine culturel'), ('nature', 'Nature et paysages'), ('art', 'Art et culture'), ('outdoor', 'Aventures en plein air'), ('spirituality', 'Spiritualité et religion'), ('entertainment', 'Divertissement et loisirs'), ('gastronomy', 'Gastronomie et cuisine locale')], max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('transport_type', models.CharField(choices=[('bus', 'Bus'), ('train', 'Train'), ('taxi', 'Taxi'), ('metro', 'Metro')], max_length=50)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamarit.site')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamarit.site')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Tamarit.models.get_image_filename, verbose_name='Image')),
                ('site', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Tamarit.site')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tamarit.site')),
            ],
        ),
    ]
