# Generated by Django 4.2.2 on 2023-06-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_profile_role_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('east', 'Eastern Region'), ('west', 'Western Region'), ('north', 'Northern Region'), ('south', 'Southern Region')], max_length=100),
        ),
    ]
